title = "Ve Mine"
baseurl = "http://vemine.org/"
publishdir = "public"
contentdir = "src/hugo/content"
layoutdir = "src/hugo/layouts"
staticdir = "src/hugo/static"
themesdir = "src/hugo/themes"
languageCode = "en-US"

[params]
  # Meta parameters.
  encoding = "utf-8"
  description = ""
  DefaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 0
languageName = "English"

[[Languages.en.menu.main]]
url    = "/#donate"
name   = "Donate"
weight = 1
[[Languages.en.menu.main]]
url    = "/#what"
name   = "What"
weight = 2
[[Languages.en.menu.main]]
url    = "/#why"
name   = "Why"
weight = 3
[[Languages.en.menu.main]]
url    = "/#how"
name   = "How"
weight = 4
[[Languages.en.menu.main]]
url    = "/#helpers"
name   = "Helpers"
weight = 5
[[Languages.en.menu.main]]
url    = "/#contact"
name   = "Contact"
weight = 6
[[Languages.en.menu.main]]
url    = "/es/"
name   = "ES"
weight = 7

[Languages.es]
weight = 1
languageName = "Español"

[[Languages.es.menu.main]]
url    = "/#donate"
name   = "Donar"
weight = 1
[[Languages.es.menu.main]]
url    = "/#what"
name   = "Que"
weight = 2
[[Languages.es.menu.main]]
url    = "/#why"
name   = "Por Que"
weight = 3
[[Languages.es.menu.main]]
url    = "/#how"
name   = "Como"
weight = 4
[[Languages.es.menu.main]]
url    = "/#helpers"
name   = "Ayudantes"
weight = 5
[[Languages.es.menu.main]]
url    = "/#contact"
name   = "Contacto"
weight = 6
[[Languages.es.menu.main]]
url    = "../"
name   = "EN"
weight = 7

[blackfriday]
  hrefTargetBlank = true


